In [ ]:
# 4 TO - DO - Task
# 4.1 Exercise on Functions:
# Task 1 – Unit Conversion Program

def unit_converter():
    """
    Converts between different units of measurement.

    The function allows the user to select a conversion type (length, weight, or volume)
    and input a value. It then performs the conversion and prints the result.

    Returns:
        float: Converted value or None if invalid input.
    """

    print("Select conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    choice = input("Enter choice (1/2/3): ")

    try:
        value = float(input("Enter value to convert: "))

        if choice == "1":
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            option = input("Choose option: ")

            if option == "1":
                result = value * 3.28084
                print("Result:", result, "ft")
                return result

            elif option == "2":
                result = value / 3.28084
                print("Result:", result, "m")
                return result

        elif choice == "2":
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            option = input("Choose option: ")

            if option == "1":
                result = value * 2.20462
                print("Result:", result, "lbs")
                return result

            elif option == "2":
                result = value / 2.20462
                print("Result:", result, "kg")
                return result

        elif choice == "3":
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            option = input("Choose option: ")

            if option == "1":
                result = value * 0.264172
                print("Result:", result, "gal")
                return result

            elif option == "2":
                result = value / 0.264172
                print("Result:", result, "L")
                return result

        else:
            print("Invalid conversion type")

    except ValueError:
        print("Invalid input. Please enter numeric values.")
        return None

In [ ]:
#Task 2 – Mathematical Operations on List

def find_sum(numbers):
    """Returns the sum of numbers in the list."""
    return sum(numbers)

def find_average(numbers):
    """Returns the average of numbers in the list."""
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """Returns the maximum value from the list."""
    return max(numbers)

def find_min(numbers):
    """Returns the minimum value from the list."""
    return min(numbers)


def math_operations():
    """
    Prompts the user to choose a mathematical operation and input numbers.
    Performs the selected operation and displays the result.
    """

    print("Choose operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter choice: ")

    try:
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if len(numbers) == 0:
            print("List cannot be empty")
            return

        if choice == "1":
            print("Sum =", find_sum(numbers))

        elif choice == "2":
            print("Average =", find_average(numbers))

        elif choice == "3":
            print("Maximum =", find_max(numbers))

        elif choice == "4":
            print("Minimum =", find_min(numbers))

        else:
            print("Invalid choice")

    except ValueError:
        print("Invalid input. Please enter numeric values.")

In [ ]:
# Exercise 4.2 – List Manipulation
def extract_every_other(lst):
    """Returns every other element starting from first."""
    return lst[::2]


def get_sublist(lst, start, end):
    """Returns sublist from start to end index inclusive."""
    return lst[start:end+1]


def reverse_list(lst):
    """Returns reversed list using slicing."""
    return lst[::-1]


def remove_first_last(lst):
    """Removes first and last element."""
    return lst[1:-1]


def get_first_n(lst, n):
    """Returns first n elements."""
    return lst[:n]


def get_last_n(lst, n):
    """Returns last n elements."""
    return lst[-n:]


def reverse_skip(lst):
    """Returns every second element from second last backwards."""
    return lst[-2::-2]

In [ ]:
# Exercise 4.3 – Nested List
def flatten(lst):
    """Flattens a nested list into a single list."""
    result = []
    for i in lst:
        if isinstance(i, list):
            result.extend(flatten(i))
        else:
            result.append(i)
    return result

In [ ]:
# Access Nested Element
def access_nested_element(lst, indices):
    """
    Returns element from nested list based on index path.
    """
    element = lst
    for i in indices:
        element = element[i]
    return element

In [ ]:
# Sum of Nested List
def sum_nested(lst):
    """Returns sum of all elements in nested list."""
    total = 0
    for i in lst:
        if isinstance(i, list):
            total += sum_nested(i)
        else:
            total += i
    return total

In [ ]:
# Remove Element from Nested List
def remove_element(lst, elem):
    """Removes all occurrences of elem from nested list."""
    result = []
    for i in lst:
        if isinstance(i, list):
            result.append(remove_element(i, elem))
        else:
            if i != elem:
                result.append(i)
    return result

In [ ]:
# Find Maximum in Nested List
def find_max(lst):
    """Finds maximum element in nested list."""
    flat = flatten(lst)
    return max(flat)

In [ ]:
# Count Occurrences
def count_occurrences(lst, elem):
    """Counts occurrences of element in nested list."""
    count = 0
    for i in lst:
        if isinstance(i, list):
            count += count_occurrences(i, elem)
        else:
            if i == elem:
                count += 1
    return count

In [ ]:
# Deep Flatten
def deep_flatten(lst):
    """Flattens deeply nested list."""
    result = []
    for i in lst:
        if isinstance(i, list):
            result.extend(deep_flatten(i))
        else:
            result.append(i)
    return result

In [ ]:
# Nested Average
def average_nested(lst):
    """Returns average of elements in nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

In [ ]:
# 10 To - Do - NumPy
# 0.1 Basic Vector and Matrix Operation with NumPy
import numpy as np

In [ ]:
# Problem 1: Array Creation
# 1. Initialize an empty array with size 2x2
arr_empty = np.empty((2,2))
print(arr_empty)

# 2. Initialize an all ones array with size 4x2
arr_ones = np.ones((4,2))
print(arr_ones)

# 3. Array filled with a specific value
arr_full = np.full((3,3), 7)
print(arr_full)

# 4. Zeros array with same shape as existing array
arr = np.array([[1,2],[3,4]])
zeros_like = np.zeros_like(arr)
print(zeros_like)

# 5. Ones array with same shape as existing array
ones_like = np.ones_like(arr)
print(ones_like)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
arr_from_list = np.array(new_list)
print(arr_from_list)

[[1.69447958e-315 0.00000000e+000]
 [4.94065646e-324 6.81879846e-310]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


In [ ]:
# Problem 2: Array Manipulation
# 1. Array from 10 to 49
arr1 = np.arange(10,50)
print(arr1)

# 2. 3x3 matrix with values 0-8
arr2 = np.arange(9).reshape(3,3)
print(arr2)

# 3. 3x3 identity matrix
identity = np.eye(3)
print(identity)

# 4. Random array size 30 and mean
rand_arr = np.random.random(30)
print(rand_arr.mean())

# 5. 10x10 random array min and max
rand_matrix = np.random.random((10,10))
print(rand_matrix.min(), rand_matrix.max())

# 6. Zero array size 10 and replace 5th element with 1
arr3 = np.zeros(10)
arr3[4] = 1
print(arr3)

# 7. Reverse array
arr4 = np.array([1,2,0,0,4,0])
print(arr4[::-1])

# 8. 2D array with border 1 and inside 0
arr5 = np.ones((5,5))
arr5[1:-1,1:-1] = 0
print(arr5)

# 9. 8x8 checkerboard
checker = np.zeros((8,8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(checker)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.4904986107795884
0.019482893493270925 0.9899462749874486
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
# Problem 3: Array Operations
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1 Add arrays
print(x + y)

# 2 Subtract arrays
print(x - y)

# 3 Multiply array with integer
print(x * 3)

# 4 Square elements
print(np.square(x))

# 5 Dot products
print("v.w =", np.dot(v,w))
print("x.v =", np.dot(x,v))
print("x.y =", np.dot(x,y))

# 6 Concatenate
print(np.vstack((x,y)))     # row
print(np.column_stack((v,w)))  # column

# 7 Concatenate x and v
try:
    print(np.concatenate((x,v)))
except ValueError as e:
    print("Error:", e)

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
v.w = 219
x.v = [29 77]
x.y = [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
# Problem 4: Matrix Operations
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [ ]:
# 1 Prove A · A⁻¹ = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)

print(identity)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
# 2 Prove AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB=\n",AB)
print("BA=\n",BA)

AB=
 [[23 13]
 [51 29]]
BA=
 [[36 44]
 [13 16]]


In [ ]:
# 3 Prove (AB)ᵀ = Bᵀ Aᵀ
left = (AB).T
right = np.dot(B.T, A.T)

print(left)
print(right)


[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


# Solve Linear Equation System
# Equations:
2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [ ]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

# Solve AX = B
X = np.linalg.solve(A,B)

print("Solution [x,y,z] =", X)

Solution [x,y,z] = [ 2.  1. -2.]


In [ ]:
# Solve using Inverse Method
A_inv = np.linalg.inv(A)

X = np.dot(A_inv,B)

print("Solution using inverse =", X)

Solution using inverse = [ 2.  1. -2.]


In [ ]:
# 10.2 Experiment – How Fast is NumPy
import numpy as np
import time

In [ ]:
# 1 Element-wise Addition
#Python List
size = 1000000

a = list(range(size))
b = list(range(size))

start = time.time()

result = [a[i] + b[i] for i in range(size)]

end = time.time()
print("Python List Addition Time:", end-start)

Python List Addition Time: 0.10418009757995605


In [ ]:
# NumPy
a = np.arange(size)
b = np.arange(size)

start = time.time()

result = a + b

end = time.time()
print("NumPy Addition Time:", end-start)

NumPy Addition Time: 0.02315807342529297


In [ ]:
# 2 Element-wise Multiplication
# Python List
start = time.time()

result = [a[i] * b[i] for i in range(size)]

end = time.time()
print("Python Multiplication Time:", end-start)

Python Multiplication Time: 0.32601308822631836


In [ ]:
# Numpy
start = time.time()

result = a * b

end = time.time()
print("NumPy Multiplication Time:", end-start)

NumPy Multiplication Time: 0.01880049705505371


In [26]:
# 3 Dot Product
#Python List
start = time.time()

dot = sum(a[i]*b[i] for i in range(size))

end = time.time()
print("Python Dot Product Time:", end-start)

Python Dot Product Time: 0.34293055534362793


In [30]:
# NumPy
start = time.time()

dot = np.dot(a,b)

end = time.time()
print("NumPy Dot Product Time:", end-start)

NumPy Dot Product Time: 0.0030231475830078125


In [31]:
# 4 Matrix Multiplication
# Python Lists
size = 1000

A = [[1]*size for _ in range(size)]
B = [[1]*size for _ in range(size)]

start = time.time()

result = [[sum(A[i][k]*B[k][j] for k in range(size)) for j in range(size)] for i in range(size)]

end = time.time()

print("Python Matrix Multiplication Time:", end-start)

Python Matrix Multiplication Time: 120.47371101379395


In [32]:
# NumPy Arrays
A = np.ones((1000,1000))
B = np.ones((1000,1000))

start = time.time()

result = np.dot(A,B)

end = time.time()

print("NumPy Matrix Multiplication Time:", end-start)

NumPy Matrix Multiplication Time: 0.08819150924682617
